# This workflow uses npm to install the dependencies, and then lints the files with Prettier.

# This workflow is adapted from the one that the Prettier project uses.
# It is licensed under the MIT license.

name: Prettier

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@bea5baf987ba7aa777a8a0b4ace377a21c45c381 # v3.8.0
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install dependencies with npm ci
        run: npm ci

      - name: Check for Prettier errors
        run: npm run prettier
